version: '3.9'

services:
  nextjs:
    container_name: hephagency-nextjs-app
    image: node:20-alpine
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
